### ISSUE TITLE
Weights are modifying the observation SD not variance

### ISSUE THREAD

**Issue by seananderson** [fate-ewi/bayesdfa#25]
SD/weight in the code:
https://github.com/fate-ewi/bayesdfa/blob/4d91db1ce5ba2ecfaa9c9152986c2987141cecac/inst/stan/dfa.stan#L625

Variance/weight in the vignette:
https://github.com/fate-ewi/bayesdfa/blob/4d91db1ce5ba2ecfaa9c9152986c2987141cecac/vignettes/a1_bayesdfa.Rmd#L325

I suppose adjusting the SD is fine and maybe the docs just need to be fixed? Or would scaling by inverse variance be more classical?

`?fit_dfa` alludes to the implementation: https://github.com/fate-ewi/bayesdfa/blob/4d91db1ce5ba2ecfaa9c9152986c2987141cecac/R/fit_dfa.R#L82-L84

**Comment by ericward-noaa** [comment]
Thanks for catching this. It's an error, because I meant to have the weights affecting the variance, not SD. Before making any changes, probably worth thinking about if this is the approach we want to use, or whether we should adopt the `glmmTMB` or `sdmTMB` style, which involves using the weights as a multiplier on the likelihood (see [here](https://github.com/glmmTMB/glmmTMB/issues/285) for a good discussion)

I can really go either way. I was thinking of this classical way initially because surveys brought into a DFA each might have an associated CV, etc. Using those as weights works with the classical implementation when likelihood is normal/lognormal, but the `glmmTMB` approach would be more general probably across families.

**Comment by seananderson** [comment]
The current implementation has been useful so far for @ecophilina 's work modelling body condition indices. It sounds like brms takes the likelihood multiplier route too. Perhaps weights should multiply the likelihood but what you currently have could be something like an input observation variance? I.e., give it a different argument name. The current implementation seems more akin to what goes into meta-analysis, which seems like a common application. If changing, I guess there would have to be a warning for a while... although given it's already not implemented exactly how it's described, a change needs to be made regardless.

**Comment by ericward-noaa** [comment]
@ecophilina -- see the changes I was thinking about here: https://github.com/fate-ewi/bayesdfa/pull/27 . Let me know if that's not clear or if there's another approach you were thinking of

**Comment by seananderson** [comment]
Looking at the implementation, it seems these are modifying the SD not the variance, right? I.e., if so, the argument should change name to inverse SD or the implementation should change to modify the variance not the SD.
https://github.com/fate-ewi/bayesdfa/blob/main/inst/stan/dfa.stan#L622

**Comment by ericward-noaa** [comment]
I'm not sure if this is just a naming issue, or something with the code that needs changing. If it's naming, we need to have 2 vectors -- one for optional likelihood weights, and one for optional inverse variance weights. Happy to change the arg name to something else.

If it's a coding issue, I think where we want to get to is that if someone has standard errors of a survey (`se`), these become the inverse variance weights $\(w_{i} = \frac{1}{{se_{i}^2}}\)$ and the variance of observations becomes $\(\frac{\sigma^2}{{w_i}}\)$, or equivalently $\(\sigma^2 \cdot (se_{i})^2\)$.

The workflow that's currently implemented is that 
1. user creates weights themselves, based on the `se` values, e.g. in the vignette https://github.com/fate-ewi/bayesdfa/blob/87765b63089dc08655e83202e9d715d597e31f09/vignettes/a1_bayesdfa.Rmd#L346 . I did this because this is the approach in `lm()` 
2. `inv_var_weights_vec` is manipulated internally to pass the `se` to Stan, https://github.com/fate-ewi/bayesdfa/blob/87765b63089dc08655e83202e9d715d597e31f09/R/fit_dfa.R#L566
3. The `inv_var_weights_vec` is used in the likelihood in Stan to have a standard deviation = $\sigma \cdot se_{i}$, I think the same as above: https://github.com/fate-ewi/bayesdfa/blob/87765b63089dc08655e83202e9d715d597e31f09/inst/stan/dfa.stan#L622

**Comment by seananderson** [comment]
Ah, I missed this line

inv_var_weights_vec = sqrt(1.0/inv_var_weights_vec),

It’s all fine then. I was confused since the vector name in the Stan code
makes it sound like it’s still the inverse variance, not the inverse SD.
