### ISSUE TITLE
Log likelihood calculation in HMM model

### ISSUE THREAD

**Issue by seananderson** [fate-ewi/bayesdfa#5]
@eric-ward: Should this be outside the loop? 
https://github.com/fate-ewi/bayesdfa/blob/master/exec/hmm_gaussian.stan#L122

@kchezik pointed that out and I think he's right.

This if statement also looks redundant:
https://github.com/fate-ewi/bayesdfa/blob/master/exec/hmm_gaussian.stan#L126-L132

**Comment by ericward-noaa** [comment]
I think the code's right. I just commented out that line, and included a loop initializing log_lik at the beginning of the generated quantities block, and the 2 approaches are perfectly correlated (with the same seed). I think because it's recursive log_lik needs to be initialized to 0 somewhere, and in the existing loop it's only accessed at the start of each time step. Is there something I'm missing? @seananderson @kchezik

And yes - the if() statement is redundant. I just commented that out and pushed the change. Shouldn't affect any results. 
https://github.com/fate-ewi/bayesdfa/commit/39479f4688d7559a665a4ad1c1176df6e18ffd15

**Comment by seananderson** [comment]
Ah, right, it’s `log_lik[t] = 0;` not `log_lik = 0;`. Missed that. I just quickly found that and assumed it was what @kchezik was talking about, but perhaps I was wrong.

**Comment by kchezik** [comment]
I may not fully understand this section but I thought it odd to add nothing to something rather than just assigning gamma[t,j]*alpha[t,j] to log_lik[t]. I assumed there may have been a mistake and a prior value should have been added. I'm not sure the code requires initialization of log_lik, I'm pretty sure you can simply log_lik[t] = gamma*alpha. It may be perfectly fine. It just didn't quite make sense to me so I mentioned it to Sean.

**Comment by ericward-noaa** [comment]
Ok, I'll leave as is. Thanks for checking out the code and let us know if you see any other issues!
